API Changes to Insert Order
cyntiafelix/Flask-SAPB1 pull request #5
Opened 2018-07-09 03:43 UTC by cyntiafelix

2018-07-25 16:35 UTC, sacabuche commented on flask_sapb1/flask_sapb1.py
> +        self.constants  = SAPbobsCOM.constants
unnecesary extra space

2018-07-25 16:51 UTC, sacabuche requested changes

2018-07-25 16:51 UTC, sacabuche commented on flask_sapb1/flask_sapb1.py
>          else:
si levanta la exception no necsitamos este else, lo podemos quitar y desindentar todo

2018-07-25 16:51 UTC, sacabuche commented on flask_sapb1/flask_sapb1.py
> +                                        SET dbo.RDR1.BaseRef = q.DocNum, dbo.RDR1.BaseType = 23, dbo.RDR1.BaseEntry = q.DocEntry
este 23 de donde sale?

2018-07-25 16:51 UTC, sacabuche commented on flask_sapb1/flask_sapb1.py
> +                orderlinkquotation_sql= """UPDATE dbo.RDR1
tal vez ponerle `link_quotation_sql`

2018-07-25 16:51 UTC, sacabuche commented on flask_sapb1/flask_sapb1.py
> +                               WHERE NumAtCard = '{0}'""".format(q['num_at_card'])
hay que pasar `num_at_card` a fetchone, para evitar ataques

2018-08-03 03:57 UTC, cyntiafelix commented on flask_sapb1/flask_sapb1.py
> +        self.constants  = SAPbobsCOM.constants
corregido

2018-08-03 03:58 UTC, cyntiafelix commented on flask_sapb1/flask_sapb1.py
>          else:
corregido

2018-08-03 04:00 UTC, cyntiafelix commented on flask_sapb1/flask_sapb1.py
> +                                        SET dbo.RDR1.BaseRef = q.DocNum, dbo.RDR1.BaseType = 23, dbo.RDR1.BaseEntry = q.DocEntry
Documentacion de SAP 9.2
http://www.saptables.net/?schema=BusinessOne9.2&module_id=7&table=RDR1
Values = -1, 0, 23=Sales Quotation

2018-08-03 04:01 UTC, cyntiafelix commented on flask_sapb1/flask_sapb1.py
> +                orderlinkquotation_sql= """UPDATE dbo.RDR1
corregido

2018-08-03 04:05 UTC, cyntiafelix commented on flask_sapb1/flask_sapb1.py
> +                               WHERE NumAtCard = '{0}'""".format(q['num_at_card'])
Corregido

2018-08-03 04:38 UTC, cyntiafelix commented
Corrections applied

2018-10-08 20:24 UTC, sacabuche approved these changes

2018-10-08 20:24 UTC, merged